BaseUrl=https://www.amazon.in/
HomePageTitle=Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in

Amazon.Search.id=twotabsearchtextbox
Amazon.SearchButton.id=nav-search-submit-button
Amazon.Search.Key=mobile smartphones under 30000

Amazon.SearchPage.ResultText.xpath=//div/h2[text()='Results']
Amazon.SearchPage.ResultText=Results
Amazon.SearchPage.SearchBoxValue.xpath=//input[@id='twotabsearchtextbox']
Amazon.SearchPage.validateText.xpath=//h2[@class='a-size-base a-spacing-small a-spacing-top-small a-text-normal']
Amazon.SearchPage.validateText.regex=(\\d+)-(\\d+) of (\\d+) results for \"%s\"

Amazon.SearchPage.Sortlist.xpath=//span[contains(@class,'a-button-text') and .//span[@class='a-dropdown-label'][text()='Sort by:']]
Amazon.Searchpage.Sortlist.newestArrival.id=s-result-sort-select_4
Amazon.SearchPage.Sortlist.resultVerify.xpath=//span[@class='a-dropdown-prompt']
Amazon.SearchPage.Sortlist.resultVerify.text=Newest Arrivals

Amazon.SearchPage.SearchResult.xpath=//div[@data-component-type='s-search-result']
Amazon.SearchPage.SponsoredLabel.xpath=.//span[contains(@class,'puis-sponsored-label-text')]
Amazon.SearchPage.ProductName.xpath=.//h2[@class='a-size-medium a-spacing-none a-color-base a-text-normal']/span
Amazon.SearchPage.ProductPrice.xpath=.//span[@class='a-price-whole']
Amazon.SearchPage.ProductPrice.prefix=\u20B9
Amazon.SearchPage.ProductPrice.fallback=Price not listed
Amazon.SearchPage.TopProducts.count=5

Amazon.ScreenShot.path=C:\Users\2479951\Desktop\AmazonMiniv3\Screenshots
